import './skills.css'

const Skills = () => {
    return (
        <div className="skills" id="skills">
            <div className="skills-wrapper">
                <h2> Key Skills </h2>
                <ul className="skills-list">
                    <li>
                        <img
                            className="skills-icon"
                            src="assets/skills/html.png"
                            alt="HTML"
                        />
                    </li>
                    <li>
                        <img
                            className="skills-icon"
                            src="assets/skills/css.png"
                            alt="CSS"
                        />
                    </li>
                    <li>
                        <img
                            className="skills-icon"
                            src="assets/skills/js.png"
                            alt="JavaScript"
                        />

                    </li>
                    <li>
                        <img
                            className="skills-icon"
                            src="assets/skills/react.png"
                            alt="React"
                        />
                    </li>
                    <li>
                        <img
                            className="skills-icon"
                            src="assets/skills/redux.png"
                            alt="Redux"
                        />
                    </li>
                    <li>
                        <img
                            className="skills-icon"
                            src="assets/skills/bootstrap.png"
                            alt="Bootstrap"
                        />
                    </li>
                    <li>
                        <img
                            className="skills-icon"
                            src="assets/skills/nodejs.png"
                            alt="NodeJS"
                        />
                    </li>
                    <li>
                        <img
                            className="skills-icon"
                            src="assets/skills/express.png"
                            alt="Express"
                        />
                    </li>
                    <li>
                        <img
                            className="skills-icon"
                            src="assets/skills/figma.png"
                            alt="Figma"
                        />
                    </li>
                    <li>
                        <img
                            className="skills-icon"
                            src="assets/skills/postgresql.png"
                            alt="PostgreSQL"
                        />
                    </li>
                    <li>
                        <img
                            className="skills-icon"
                            src="assets/skills/mongodb.png"
                            alt="MongoDB"
                        />
                    </li>
                    <li>
                        <img
                            className="skills-icon"
                            src="assets/skills/docker.png"
                            alt="Docker"
                        />
                    </li>
                    <li>
                        <img
                            className="skills-icon"
                            src="assets/skills/github.png"
                            alt="Github"
                        />
                    </li>
                    <li>
                        <img
                            className="skills-icon"
                            src="assets/skills/tdd.png"
                            alt="TDD"
                        />
                    </li>
                    <li>
                        <img
                            className="skills-icon"
                            src="assets/skills/aws.png"
                            alt="AWS"
                        />
                    </li>
                </ul></div>
        </div>
    )
}

export default Skills
